#!/usr/bin/env ruby
begin
    Dir.chdir ARGV.shift do
        IO.popen(ARGV, {:err => [:child, :out]}) do |pipe|
            puts pipe.read
        end
        exit $?.exitstatus
    end
rescue Exception => e
    puts e
    exit 1
end
